
function torque_controller_config(this_block)

  % Revision History:
  %
  %   10-Mar-2013  (22:07 hours):
  %     Original code was machine generated by Xilinx's System Generator after parsing
  %     E:\Matlab\hdlsrc\torque_controller.vhd
  %
  %

  this_block.setTopLevelLanguage('VHDL');

  this_block.setEntityName('torque_controller');

  % System Generator has to assume that your entity  has a combinational feed through; 
  %   if it  doesn't, then comment out the following line:
  this_block.tagAsCombinational;

  this_block.addSimulinkInport('clk');
  this_block.addSimulinkInport('reset');
  this_block.addSimulinkInport('clk_enable');
  this_block.addSimulinkInport('err');
  this_block.addSimulinkInport('kp');
  this_block.addSimulinkInport('ki');
  this_block.addSimulinkInport('kd');
  this_block.addSimulinkInport('reset_int');

  this_block.addSimulinkOutport('ce_out');
  this_block.addSimulinkOutport('cmd');

  ce_out_port = this_block.port('ce_out');
  ce_out_port.setType('UFix_1_0');
  ce_out_port.useHDLVector(false);
  cmd_port = this_block.port('cmd');
  cmd_port.setType('UFix_32_0');

  % -----------------------------
  if (this_block.inputTypesKnown)
    % do input type checking, dynamic output type and generic setup in this code block.

    if (this_block.port('clk').width ~= 1);
      this_block.setError('Input data type for port "clk" must have width=1.');
    end

    this_block.port('clk').useHDLVector(false);

    if (this_block.port('reset').width ~= 1);
      this_block.setError('Input data type for port "reset" must have width=1.');
    end

    this_block.port('reset').useHDLVector(false);

    if (this_block.port('clk_enable').width ~= 1);
      this_block.setError('Input data type for port "clk_enable" must have width=1.');
    end

    this_block.port('clk_enable').useHDLVector(false);

    if (this_block.port('err').width ~= 32);
      this_block.setError('Input data type for port "err" must have width=32.');
    end

    if (this_block.port('kp').width ~= 32);
      this_block.setError('Input data type for port "kp" must have width=32.');
    end

    if (this_block.port('ki').width ~= 32);
      this_block.setError('Input data type for port "ki" must have width=32.');
    end

    if (this_block.port('kd').width ~= 32);
      this_block.setError('Input data type for port "kd" must have width=32.');
    end

    if (this_block.port('reset_int').width ~= 1);
      this_block.setError('Input data type for port "reset_int" must have width=1.');
    end

    this_block.port('reset_int').useHDLVector(false);

  end  % if(inputTypesKnown)
  % -----------------------------

  % System Generator found no apparent clock signals in the HDL, assuming combinational logic.
  % -----------------------------
   if (this_block.inputRatesKnown)
     inputRates = this_block.inputRates; 
     uniqueInputRates = unique(inputRates); 
     outputRate = uniqueInputRates(1);
     for i = 2:length(uniqueInputRates)
       if (uniqueInputRates(i) ~= Inf)
         outputRate = gcd(outputRate,uniqueInputRates(i));
       end
     end  % for(i)
     for i = 1:this_block.numSimulinkOutports 
       this_block.outport(i).setRate(outputRate); 
     end  % for(i)
   end  % if(inputRatesKnown)
  % -----------------------------

    % (!) Set the inout port rate to be the same as the first input 
    %     rate. Change the following code if this is untrue.
    uniqueInputRates = unique(this_block.getInputRates);


  % Add addtional source files as needed.
  %  |-------------
  %  | Add files in the order in which they should be compiled.
  %  | If two files "a.vhd" and "b.vhd" contain the entities
  %  | entity_a and entity_b, and entity_a contains a
  %  | component of type entity_b, the correct sequence of
  %  | addFile() calls would be:
  %  |    this_block.addFile('b.vhd');
  %  |    this_block.addFile('a.vhd');
  %  |-------------

  %    this_block.addFile('');
  %    this_block.addFile('');
  this_block.addFile('hdlsrc/difference.vhd');
  this_block.addFile('hdlsrc/torque_controller.vhd');

return;


